### ISSUE TITLE
Objective-c support

### ISSUE THREAD

**Issue by quard8** [LowKostKustomz/StatusAlert#1]
Do you have plans to add Obj-C support?

**Comment by LowKostKustomz** [comment]
Of course, it will be added as fast as possible, likely tomorrow, so stay tuned:)

**Comment by LowKostKustomz** [comment]
Objective-C support was added to the version 0.10.0 with some source-breaking changes, check out [release notes](https://github.com/LowKostKustomz/StatusAlert/releases/tag/0.10.0) for more details.
