### ISSUE TITLE
framework not found Pods_StatusAlertObjCDemo

### ISSUE THREAD

**Issue by JulesMoorhouse** [LowKostKustomz/StatusAlert#3]
I'm getting the follow error, can't get passed it.

ld: framework not found Pods_StatusAlertObjCDemo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by LowKostKustomz** [comment]
Try to close StatusAlert project, run `pod install` command in terminal from `StatusAlert/Example` folder and after that open `StatusAlert.xcworkspace` file, **NOT** `StatusAlert.xcodeproj`. 

Hope it will help, if not - feel free to reply here, I'll try to help you.
