### ISSUE TITLE
StatusAlert object is not deinit

### ISSUE THREAD

**Issue by RSickenberg** [LowKostKustomz/StatusAlert#4]
![image](https://user-images.githubusercontent.com/16922548/42535910-092aae32-8491-11e8-9440-5b22268599b1.png)

Version : 0.12.0

**Comment by LowKostKustomz** [comment]
Hi, could you please provide me code that presents alert and what are you doing?

**Comment by LowKostKustomz** [comment]
And all the code related to StatusAlert, setup, timings, and all the things that could help me identify the bug.

**Comment by RSickenberg** [comment]
```
let likeAlert = StatusAlert()

... 

noFavorites.image = #imageLiteral(resourceName: "DislikeFullHighRes")
noFavorites.title = "Oh!"
noFavorites.message = "It seems you don't have any favorties. Go love your favorites on the ❤️ top right corner."
noFavorites.canBePickedOrDismissed = true
noFavorites.appearance = .copyCommon()
noFavorites.alertShowingDuration = TimeInterval(exactly: 5)!
```

**Comment by LowKostKustomz** [comment]
I think I get your problem: you are calling `show` method multiple times on one instance of `StatusAlert`, am I right?

If so then there is the rule for now: you should create new instance of alert for every new alert you want to present. I will fix this in a few days and distribute the fix, so stay tuned.

If this is not your problem then reply with some additional info.

**Comment by RSickenberg** [comment]
You are right, Thanks for the fix, I update to the new version when she is ready :)

Thanks for taking time with me ! 😄

**Comment by LowKostKustomz** [comment]
You are welcome!

**Comment by LowKostKustomz** [comment]
The issue was fixed in version [0.12.1](https://github.com/LowKostKustomz/StatusAlert/releases/tag/0.12.1).

Now you can present the same instance of alert multiple times.

> **NOTE**
> - more than one presentation of one instance of alert at the same time is not allowed and will be ignored;

**Comment by RSickenberg** [comment]
Thanks @LowKostKustomz !

**Comment by RSickenberg** [comment]
Hello @LowKostKustomz, thanks for your upgrade, but I have a new bug, when I keep init my view and I switch from a new tab and recall the Alert, I cannot dismiss it anymore, is it from my side?

**Comment by LowKostKustomz** [comment]
It depends on your code, could you please provide more detailed description of your bug what you are doing and show me the code that probably can cause the issue?

Also you can try to go to source files of my library and set a breakpoint to dismiss method and see if it is called. Try to debug it from the inside of my library and step by step getting up to your code, maybe some of your methods is not called.

**Comment by RSickenberg** [comment]
I begin my ViewController with an instantiation of StatusAlert 
`let likeAlert = StatusAlert()`

I call a method `onViewDidLoad` with those lines

`
StatusAlert.multiplePresentationsBehavior = .dismissCurrentlyPresented
`
`
methodName()
`
```
func methodName() {
    likeAlert.canBePickedOrDismissed = true
    likeAlert.alertShowingDuration = TimeInterval(exactly: 2)!
}
```

And that's it when I recall my StatusAlert if I didn't deinit (back to root) the status alert doesn't dismiss itself
