### ISSUE TITLE
Request: can you provide a way to customize the size of the alert?

### ISSUE THREAD

**Issue by haitaozz** [LowKostKustomz/StatusAlert#9]
I would love to be able to make the alert a bit smaller.
Thank you!

**Comment by LowKostKustomz** [comment]
Hi! Alert size is calculated by AutoLayout mechanism depending on the content size and insets/offsets. So you can try to edit:
 - `StatusAlert. SizesAndDistances` values to edit offsets, insets and sizes;
 - `StatusAlert. Appearance` values to edit fonts and make labels content smaller.
 
 Each of them has `common` static property that is copied to every newly created alert. So to change values for all new alerts you can edit `.common` parameters.
 
Or you can access `appearance` and `sizesAndDistances` properties of the particular alert instance to edit that single instance and do not affect new alerts.
